automountServiceAccountToken: false
priorityClassName: system-node-critical

image:
  repository: tcinternal/eks-nvme-ssd-provisioner
  pullPolicy: IfNotPresent
  tag: stable

imagePullSecrets: {}
nameOverride: ""
fullnameOverride: ""

securityContext: 
  privileged: true

nodeSelector:
  aws.amazon.com/eks-local-ssd: "true"

tolerations: {}
